# -------------------------------------------------------------------------
#  This file is part of the MindStudio project.
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
#
# MindStudio is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#         http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# --------------------------------------------------------------------------------------------#

import networkx as nx
from backend.kgi.core.comparealg.anchor_compare_all_alg import AnchorCompareAllAlg
from backend.kgi.core.structs.node import Node

def _create_node(node_id: int, node_feature: str) -> Node:
    node = Node()
    node.set_node_id(node_id)
    node.set_node_feature(node_feature)
    return node

class TestAnchorCompareAllAlg:
    def test_node_only_in_left(self):
        # 有个节点只在左图中出现
        left_node1 = _create_node(1, "add")
        left_node2 = _create_node(2, "sub")
        left_node3 = _create_node(3, "sub")
        left_node4 = _create_node(4, "mul")
        left_node5 = _create_node(5, "mul")
        left_node6 = _create_node(6, "div")
        left_node7 = _create_node(7, "div")
        left_node8 = _create_node(8, "mul")
        left_graph = nx.DiGraph()
        left_graph.add_edge(left_node1, left_node2)
        left_graph.add_edge(left_node1, left_node3)
        left_graph.add_edge(left_node2, left_node4)
        left_graph.add_edge(left_node3, left_node5)
        left_graph.add_edge(left_node4, left_node6)
        left_graph.add_edge(left_node5, left_node7)
        left_graph.add_edge(left_node6, left_node8)

        right_node1 = _create_node(1, "add")
        right_node2 = _create_node(2, "sub")
        right_node3 = _create_node(3, "sub")
        right_node4 = _create_node(4, "mul")
        right_node5 = _create_node(5, "mul")
        right_node6 = _create_node(6, "div")
        right_node7 = _create_node(7, "div")
        right_graph = nx.DiGraph()
        right_graph.add_edge(right_node1, right_node2)
        right_graph.add_edge(right_node1, right_node3)
        right_graph.add_edge(right_node2, right_node4)
        right_graph.add_edge(right_node3, right_node5)
        right_graph.add_edge(right_node4, right_node6)
        right_graph.add_edge(right_node5, right_node7)

        alg = AnchorCompareAllAlg(left_graph, right_graph, None, None, False, False)
        alg.compare()

        assert left_node1 in alg.get_left_match_nodes()
        assert right_node1 in alg.get_right_match_nodes()
        assert left_node2 in alg.get_left_match_nodes()
        assert right_node2 in alg.get_right_match_nodes()
        assert left_node3 in alg.get_left_match_nodes()
        assert right_node3 in alg.get_right_match_nodes()
        assert left_node4 in alg.get_left_match_nodes()
        assert right_node4 in alg.get_right_match_nodes()
        assert left_node5 in alg.get_left_match_nodes()
        assert right_node5 in alg.get_right_match_nodes()
        assert left_node6 in alg.get_left_mismatch_nodes()
        assert right_node6 in alg.get_right_mismatch_nodes()
        assert left_node7 in alg.get_left_mismatch_nodes()
        assert right_node7 in alg.get_right_mismatch_nodes()
        assert left_node8 in alg.get_left_mismatch_nodes()

    def test_node_only_in_right(self):
        # 有个节点只在右图中出现
        left_node1 = _create_node(1, "add")
        left_node2 = _create_node(2, "sub")
        left_node3 = _create_node(3, "sub")
        left_node4 = _create_node(4, "mul")
        left_node5 = _create_node(5, "mul")
        left_node6 = _create_node(6, "div")
        left_node7 = _create_node(7, "div")
        left_graph = nx.DiGraph()
        left_graph.add_edge(left_node1, left_node2)
        left_graph.add_edge(left_node1, left_node3)
        left_graph.add_edge(left_node2, left_node4)
        left_graph.add_edge(left_node3, left_node5)
        left_graph.add_edge(left_node4, left_node6)
        left_graph.add_edge(left_node5, left_node7)

        right_node1 = _create_node(1, "add")
        right_node2 = _create_node(2, "sub")
        right_node3 = _create_node(3, "sub")
        right_node4 = _create_node(4, "mul")
        right_node5 = _create_node(5, "mul")
        right_node6 = _create_node(6, "div")
        right_node7 = _create_node(7, "div")
        right_node8 = _create_node(8, "mul")
        right_graph = nx.DiGraph()
        right_graph.add_edge(right_node1, right_node2)
        right_graph.add_edge(right_node1, right_node3)
        right_graph.add_edge(right_node2, right_node4)
        right_graph.add_edge(right_node3, right_node5)
        right_graph.add_edge(right_node4, right_node6)
        right_graph.add_edge(right_node5, right_node7)
        right_graph.add_edge(right_node6, right_node8)

        alg = AnchorCompareAllAlg(left_graph, right_graph, None, None, False, False)
        alg.compare()

        assert left_node1 in alg.get_left_match_nodes()
        assert right_node1 in alg.get_right_match_nodes()
        assert left_node2 in alg.get_left_match_nodes()
        assert right_node2 in alg.get_right_match_nodes()
        assert left_node3 in alg.get_left_match_nodes()
        assert right_node3 in alg.get_right_match_nodes()
        assert left_node4 in alg.get_left_match_nodes()
        assert right_node4 in alg.get_right_match_nodes()
        assert left_node5 in alg.get_left_match_nodes()
        assert right_node5 in alg.get_right_match_nodes()
        assert left_node6 in alg.get_left_mismatch_nodes()
        assert right_node6 in alg.get_right_mismatch_nodes()
        assert left_node7 in alg.get_left_mismatch_nodes()
        assert right_node7 in alg.get_right_mismatch_nodes()
        assert right_node8 in alg.get_right_mismatch_nodes()

    def test_no_diff(self):
        # 没有差异
        left_node1 = _create_node(1, "add")
        left_node2 = _create_node(2, "sub")
        left_node3 = _create_node(3, "sub")
        left_node4 = _create_node(4, "mul")
        left_node5 = _create_node(5, "mul")
        left_node6 = _create_node(6, "div")
        left_node7 = _create_node(7, "div")
        left_node8 = _create_node(8, "mul")
        left_graph = nx.DiGraph()
        left_graph.add_edge(left_node1, left_node2)
        left_graph.add_edge(left_node1, left_node3)
        left_graph.add_edge(left_node2, left_node4)
        left_graph.add_edge(left_node3, left_node5)
        left_graph.add_edge(left_node4, left_node6)
        left_graph.add_edge(left_node5, left_node7)
        left_graph.add_edge(left_node6, left_node8)

        right_node1 = _create_node(1, "add")
        right_node2 = _create_node(2, "sub")
        right_node3 = _create_node(3, "sub")
        right_node4 = _create_node(4, "mul")
        right_node5 = _create_node(5, "mul")
        right_node6 = _create_node(6, "div")
        right_node7 = _create_node(7, "div")
        right_node8 = _create_node(8, "mul")
        right_graph = nx.DiGraph()
        right_graph.add_edge(right_node1, right_node2)
        right_graph.add_edge(right_node1, right_node3)
        right_graph.add_edge(right_node2, right_node4)
        right_graph.add_edge(right_node3, right_node5)
        right_graph.add_edge(right_node4, right_node6)
        right_graph.add_edge(right_node5, right_node7)
        right_graph.add_edge(right_node6, right_node8)

        alg = AnchorCompareAllAlg(left_graph, right_graph, None, None, False, False)
        alg.compare()

        assert left_node1 in alg.get_left_match_nodes()
        assert right_node1 in alg.get_right_match_nodes()
        assert left_node2 in alg.get_left_match_nodes()
        assert right_node2 in alg.get_right_match_nodes()
        assert left_node3 in alg.get_left_match_nodes()
        assert right_node3 in alg.get_right_match_nodes()
        assert left_node4 in alg.get_left_match_nodes()
        assert right_node4 in alg.get_right_match_nodes()
        assert left_node5 in alg.get_left_match_nodes()
        assert right_node5 in alg.get_right_match_nodes()
        assert left_node6 in alg.get_left_match_nodes()
        assert right_node6 in alg.get_right_match_nodes()
        assert left_node7 in alg.get_left_match_nodes()
        assert right_node7 in alg.get_right_match_nodes()
        assert left_node8 in alg.get_left_match_nodes()
        assert right_node8 in alg.get_right_match_nodes()

    def test_more_one_edge(self):
        # 左图比右图多了一条边
        left_node1 = _create_node(1, "add")
        left_node2 = _create_node(2, "sub")
        left_node3 = _create_node(3, "sub")
        left_node4 = _create_node(4, "mul")
        left_node5 = _create_node(5, "mul")
        left_node6 = _create_node(6, "div")
        left_node7 = _create_node(7, "div")
        left_node8 = _create_node(8, "mul")
        left_graph = nx.DiGraph()
        left_graph.add_edge(left_node1, left_node2)
        left_graph.add_edge(left_node1, left_node3)
        left_graph.add_edge(left_node2, left_node4)
        left_graph.add_edge(left_node3, left_node5)
        left_graph.add_edge(left_node4, left_node6)
        left_graph.add_edge(left_node5, left_node7)
        left_graph.add_edge(left_node6, left_node8)
        left_graph.add_edge(left_node7, left_node8)

        right_node1 = _create_node(1, "add")
        right_node2 = _create_node(2, "sub")
        right_node3 = _create_node(3, "sub")
        right_node4 = _create_node(4, "mul")
        right_node5 = _create_node(5, "mul")
        right_node6 = _create_node(6, "div")
        right_node7 = _create_node(7, "div")
        right_node8 = _create_node(8, "mul")
        right_graph = nx.DiGraph()
        right_graph.add_edge(right_node1, right_node2)
        right_graph.add_edge(right_node1, right_node3)
        right_graph.add_edge(right_node2, right_node4)
        right_graph.add_edge(right_node3, right_node5)
        right_graph.add_edge(right_node4, right_node6)
        right_graph.add_edge(right_node5, right_node7)
        right_graph.add_edge(right_node6, right_node8)

        alg = AnchorCompareAllAlg(left_graph, right_graph, None, None, False, False)
        alg.compare()

        assert left_node1 in alg.get_left_match_nodes()
        assert right_node1 in alg.get_right_match_nodes()
        assert left_node2 in alg.get_left_match_nodes()
        assert right_node2 in alg.get_right_match_nodes()
        assert left_node3 in alg.get_left_match_nodes()
        assert right_node3 in alg.get_right_match_nodes()
        assert left_node4 in alg.get_left_match_nodes()
        assert right_node4 in alg.get_right_match_nodes()
        assert left_node5 in alg.get_left_match_nodes()
        assert right_node5 in alg.get_right_match_nodes()
        assert left_node6 in alg.get_left_mismatch_nodes()
        assert right_node6 in alg.get_right_mismatch_nodes()
        assert left_node7 in alg.get_left_mismatch_nodes()
        assert right_node7 in alg.get_right_mismatch_nodes()
        assert left_node8 in alg.get_left_mismatch_nodes()
        assert right_node8 in alg.get_right_mismatch_nodes()

    def test_compare_up(self):
        # 向上比较
        left_node1 = _create_node(1, "sub")
        left_node2 = _create_node(2, "sub")
        left_node3 = _create_node(3, "sub")
        left_node4 = _create_node(4, "mul")
        left_node5 = _create_node(5, "mul")
        left_node6 = _create_node(6, "div")
        left_node7 = _create_node(7, "div")
        left_node8 = _create_node(8, "mul")
        left_graph = nx.DiGraph()
        left_graph.add_edge(left_node1, left_node2)
        left_graph.add_edge(left_node1, left_node3)
        left_graph.add_edge(left_node2, left_node4)
        left_graph.add_edge(left_node3, left_node5)
        left_graph.add_edge(left_node4, left_node6)
        left_graph.add_edge(left_node5, left_node7)
        left_graph.add_edge(left_node6, left_node8)

        right_node1 = _create_node(1, "add")
        right_node2 = _create_node(2, "sub")
        right_node3 = _create_node(3, "sub")
        right_node4 = _create_node(4, "mul")
        right_node5 = _create_node(5, "mul")
        right_node6 = _create_node(6, "div")
        right_node7 = _create_node(7, "div")
        right_node8 = _create_node(8, "mul")
        right_graph = nx.DiGraph()
        right_graph.add_edge(right_node1, right_node2)
        right_graph.add_edge(right_node1, right_node3)
        right_graph.add_edge(right_node2, right_node4)
        right_graph.add_edge(right_node3, right_node5)
        right_graph.add_edge(right_node4, right_node6)
        right_graph.add_edge(right_node5, right_node7)
        right_graph.add_edge(right_node6, right_node8)

        alg = AnchorCompareAllAlg(left_graph, right_graph, None, None, False, True)
        alg.compare()

        assert left_node1 in alg.get_left_mismatch_nodes()
        assert right_node1 in alg.get_right_mismatch_nodes()
        assert left_node2 in alg.get_left_mismatch_nodes()
        assert right_node2 in alg.get_right_mismatch_nodes()
        assert left_node3 in alg.get_left_mismatch_nodes()
        assert right_node3 in alg.get_right_mismatch_nodes()
        assert left_node4 in alg.get_left_match_nodes()
        assert right_node4 in alg.get_right_match_nodes()
        assert left_node5 in alg.get_left_match_nodes()
        assert right_node5 in alg.get_right_match_nodes()
        assert left_node6 in alg.get_left_match_nodes()
        assert right_node6 in alg.get_right_match_nodes()
        assert left_node7 in alg.get_left_match_nodes()
        assert right_node7 in alg.get_right_match_nodes()
        assert left_node8 in alg.get_left_match_nodes()
        assert right_node8 in alg.get_right_match_nodes()